# Rustfmt configuration for HelixML

# Basic formatting
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments
wrap_comments = true
comment_width = 80
normalize_comments = true

# Code style
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false

# Advanced
format_code_in_doc_comments = true
format_strings = true
format_macro_matchers = true
format_generated_files = false

# Unstable features (requires nightly)
# unstable_features = true
# format_macro_bodies = true
