[book]
title = "🌀 HelixML Documentation"
description = "Advanced machine learning framework with SSM, Hyena, and Meaning Induction"
authors = ["Alex B <dropwizards@gmail.com>"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/blackterrordistro/helix-ml"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/blackterrordistro/helix-ml/edit/master/docs/book/src/{path}"
additional-css = ["custom.css"]

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[preprocessor.links]

[preprocessor.index]

[preprocessor.syntax-highlighting]
default-theme = "navy"
